# Generated by Django 4.1.6 on 2024-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bebederos',
            fields=[
                ('id_bebedero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('institucion', models.CharField(blank=True, max_length=100)),
                ('palabras_clave', models.CharField(blank=True, max_length=500)),
                ('descripcion', models.CharField(blank=True, default='', max_length=1000)),
                ('latitud', models.FloatField(blank=True, default=None, max_length=100, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
