# Generated by Django 4.1.6 on 2024-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0002_bebederos_nueva_var'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebederos',
            old_name='nueva_var',
            new_name='estado',
        ),
    ]
