# Generated by Django 4.1.6 on 2024-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0004_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='dato_extra',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
